#!/usr/bin/env bash
if [ "$DEBUG" = "1" ] ; then
	hhvm -m debug -d hhvm.hack.lang.look_for_typechecker=false -c hhvm.ini phpunit.phar $@
else
	hhvm -d hhvm.hack.lang.look_for_typechecker=false -c hhvm.ini phpunit.phar $@
fi

